export default {
    UPDATE_PLAYING: "UPDATE_PLAYING",
    UPDATE_BUFFERING: "UPDATE_BUFFERING",
    SET_INIT: "SET_INIT",
    SET_SEEKING: "SET_SEEKING",
    SET_FIRST_TRACK: "SET_FIRST_TRACK",

    FETCH_MUSICS: "FETCH_MUSICS",
    FETCH_MORE_MUSICS: "FETCH_MORE_MUSICS"
}