export default {
    UPDATE_PLAYING: "UPDATE_PLAYING",
    UPDATE_BUFFERING: "UPDATE_BUFFERING",
    SET_INIT: "SET_INIT",

    FETCH_MUSICS: "FETCH_MUSICS",
    FETCH_MORE_MUSICS: "FETCH_MORE_MUSICS"
}